version: '3.3'

services:
   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: 1
       MYSQL_DATABASE: wordpress
       MYSQL_USER: root
       MYSQL_PASSWORD: 1

   wordpress5:
     depends_on:
       - db
     build:
       context: .
       dockerfile: Dockerfile
     ports:
       - "8001:80"
     volumes:
       - ${PROJECT_FOLDER}:/var/www/html/
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: root
       WORDPRESS_DB_PASSWORD: 1
   wordpress7:
     depends_on:
       - db
     image: wordpress:php7.1-apache
     ports:
       - "8000:80"
     volumes:
       - ${PROJECT_FOLDER}:/var/www/html/
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: root
       WORDPRESS_DB_PASSWORD: 1
volumes:
    db_data:
